CREATE DATABASE LAB_SESION_23

USE DATABASE LAB_SESION_23;
CREATE SCHEMA LAB_Ironhack;


USE SCHEMA LAB_SESION_23.LAB_Ironhack;
CREATE TABLE FACTURAS (
    id_factura VARCHAR(50),
    fecha_factura DATE,
    id_coche VARCHAR(50),
    id_cliente VARCHAR(50),
    id_vendedor VARCHAR(50)
);

CREATE TABLE COCHES (
    id_coche VARCHAR(50),
    fabricante_coche VARCHAR(50),
    modelo_coche VARCHAR(50),
    year_coche VARCHAR(50),
    color_coche VARCHAR(50)
);

CREATE TABLE CLIENTES (
    id_cliente VARCHAR(50),
    nombre_cliente VARCHAR(50),
    telefono_cliente VARCHAR(50),
    correo_cliente VARCHAR(50),
    direccion_cliente VARCHAR(50),
    ciudad_cliente VARCHAR(50),
    provincia_cliente VARCHAR(50),
    pais_cliente VARCHAR(50),
    codigopostal_cliente VARCHAR(50)
    );

CREATE TABLE VENDEDORES (
    id_vendedor VARCHAR(50),
    nombre_vendedor VARCHAR(50),
    tienda_vendedor VARCHAR(50)
);

ALTER TABLE COCHES 
ADD ID INT PRIMARY KEY;

ALTER TABLE CLIENTES
ADD ID INT PRIMARY KEY;

ALTER TABLE VENDEDORES
ADD ID INT PRIMARY KEY;

ALTER TABLE FACTURAS
ADD ID INT PRIMARY KEY;

ALTER TABLE COCHES
RENAME COLUMN ID TO COCHE_ID;

ALTER TABLE CLIENTES
RENAME COLUMN ID TO CLIENTE_ID;

ALTER TABLE VENDEDORES
RENAME COLUMN ID TO VENDEDOR_ID;

ALTER TABLE FACTURAS
RENAME COLUMN ID_COCHE TO COCHE_ID;

ALTER TABLE FACTURAS
RENAME COLUMN ID_CLIENTE TO CLIENTE_ID;

ALTER TABLE FACTURAS
RENAME COLUMN ID_VENDEDOR TO VENDEDOR_ID;